#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef BLUESDK_SWIFT_H
#define BLUESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BlueSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

enum AlarmRunState : NSInteger;
/// 闹钟信息
/// Alarm info
SWIFT_CLASS("_TtC7BlueSDK9AlarmInfo")
@interface AlarmInfo : NSObject
/// 闹钟槽位索引（1~7）/ Alarm slot index (1~7)
@property (nonatomic, readonly) NSInteger index;
/// 使能状态（true=开启, false=关闭）/ Enabled state
@property (nonatomic, readonly) BOOL isEnabled;
/// 小时（0~23）/ Hour (0~23)
@property (nonatomic, readonly) NSInteger hour;
/// 分钟（0~59）/ Minute (0~59)
@property (nonatomic, readonly) NSInteger minute;
/// 星期周期掩码 / Week repeat bitmask
@property (nonatomic, readonly) NSInteger weekMask;
/// 响铃状态：0=空闲, 1=响铃结束 / Ringing state: 0=idle, 1=ended
@property (nonatomic, readonly) NSInteger ringingState;
/// 事件状态：0=无, 1=响铃中, 2=超时或已取药 / Event status: 0=none, 1=ringing, 2=timeout/taken
@property (nonatomic, readonly) NSInteger eventStatus;
- (nonnull instancetype)initWithIndex:(NSInteger)index isEnabled:(BOOL)isEnabled hour:(NSInteger)hour minute:(NSInteger)minute weekMask:(NSInteger)weekMask ringingState:(NSInteger)ringingState eventStatus:(NSInteger)eventStatus OBJC_DESIGNATED_INITIALIZER;
/// 向后兼容旧字段 / Backward compatible
@property (nonatomic, readonly) NSInteger advanceStatus;
/// 是否为无效/删除状态（未使能或时间超出有效范围）
@property (nonatomic, readonly) BOOL isDeleted;
/// 当前运行状态 / Current running state
@property (nonatomic, readonly) enum AlarmRunState runState;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 闹钟运行状态
/// Alarm running state
typedef SWIFT_ENUM(NSInteger, AlarmRunState, open) {
/// 空闲/等待下次触发 / Idle, waiting for next trigger
  AlarmRunStateIdle = 0,
/// 正在响铃中 / Currently ringing
  AlarmRunStateRinging = 1,
/// 响铃结束（超时或已取药）/ Ringing ended (timeout or taken)
  AlarmRunStateEnded = 2,
};

enum LogLevel : NSInteger;
enum PermissionStatus : NSInteger;
enum ConnectionState : NSInteger;
/// BlueSDK 主入口，采用单例模式
/// 使用方式：<code>BlueSDKManager.shared.initialize()</code>
SWIFT_CLASS("_TtC7BlueSDK14BlueSDKManager")
@interface BlueSDKManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BlueSDKManager * _Nonnull shared;)
+ (BlueSDKManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 销毁 SDK，释放所有 BLE 资源（FR33）
- (void)destroy;
- (void)setLogLevel:(enum LogLevel)level;
/// 清空日志缓冲区
- (void)clearLogBuffer;
/// 查询蓝牙权限状态（FR07）
- (enum PermissionStatus)checkPermissions SWIFT_WARN_UNUSED_RESULT;
/// 当前连接状态（FR06）
@property (nonatomic, readonly) enum ConnectionState connectionState;
/// 停止扫描（FR01）
- (void)stopScan;
/// 断开连接（FR03）
- (void)disconnect;
@end

/// BLE 连接状态枚举
/// 状态转换通过 ConnectionManager 统一管理（ARCH-07）
typedef SWIFT_ENUM(NSInteger, ConnectionState, open) {
/// 已断开（初始状态）
  ConnectionStateDisconnected = 0,
/// 连接中
  ConnectionStateConnecting = 1,
/// 已连接（未认证）
  ConnectionStateConnected = 2,
/// 已认证（可执行业务指令）
  ConnectionStateAuthenticated = 3,
/// 重连中（断线后自动重连）
  ConnectionStateReconnecting = 4,
};

@class NSString;
/// 设备基础信息
SWIFT_CLASS("_TtC7BlueSDK10DeviceInfo")
@interface DeviceInfo : NSObject
/// 固件版本号（如 “1.0.0”）
@property (nonatomic, readonly, copy) NSString * _Nonnull firmwareVersion;
/// 设备 MAC 地址字符串（如 “6F:74:36:74:74:64”）
@property (nonatomic, readonly, copy) NSString * _Nonnull macAddressString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK 日志级别
typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
/// 关闭所有日志（默认）
  LogLevelNone = 0,
/// 仅错误日志
  LogLevelError = 1,
/// 警告及以上
  LogLevelWarn = 2,
/// 信息及以上
  LogLevelInfo = 3,
/// 调试及以上（输出原始帧数据）
  LogLevelDebug = 4,
};

/// Real-time medication notification type from device
/// Sent when device alarm state changes (ringing / timeout / taken)
typedef SWIFT_ENUM(NSInteger, MedicationNotificationType, open) {
/// Alarm started ringing, waiting for user to take medication
  MedicationNotificationTypeRinging = 1,
/// Alarm timed out, user did not take medication in time
  MedicationNotificationTypeTimeout = 2,
/// User took medication (confirmed by device sensor)
  MedicationNotificationTypeTaken = 3,
};

enum MedicationStatus : NSInteger;
/// 用药记录
SWIFT_CLASS("_TtC7BlueSDK16MedicationRecord")
@interface MedicationRecord : NSObject
/// 实际事件时间戳（Unix 时间戳，毫秒）— 取药/漏服发生的时刻
@property (nonatomic, readonly) int64_t timestamp;
/// 对应的闹钟槽位索引（1~7）
@property (nonatomic, readonly) NSInteger alarmIndex;
/// 闹钟设定小时（0~23）— 应该吃药的时间
@property (nonatomic, readonly) NSInteger alarmHour;
/// 闹钟设定分钟（0~59）
@property (nonatomic, readonly) NSInteger alarmMinute;
/// 用药状态（取药/超时/漏服/提前）
@property (nonatomic, readonly) enum MedicationStatus status;
- (nonnull instancetype)initWithTimestamp:(int64_t)timestamp alarmIndex:(NSInteger)alarmIndex alarmHour:(NSInteger)alarmHour alarmMinute:(NSInteger)alarmMinute status:(enum MedicationStatus)status OBJC_DESIGNATED_INITIALIZER;
/// 闹钟设定时间格式化（如 “08:00”）
@property (nonatomic, readonly, copy) NSString * _Nonnull alarmTimeString;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 用药结果状态枚举
/// Medication result status enum
/// 对应协议中的状态值
/// Maps to protocol status values
typedef SWIFT_ENUM(NSInteger, MedicationStatus, open) {
/// 按时取药（0x01）/ Taken on time (0x01)
  MedicationStatusTaken = 1,
/// 超时取药（0x02）/ Taken late (0x02)
  MedicationStatusTimeout = 2,
/// 漏服（0x03）/ Missed (0x03)
  MedicationStatusMissed = 3,
/// 提前取药（0x04）/ Taken early (0x04)
  MedicationStatusEarly = 4,
};

/// 蓝牙权限状态（与 Android PermissionStatus 对称）
typedef SWIFT_ENUM(NSInteger, PermissionStatus, open) {
/// 已授权
  PermissionStatusGranted = 0,
/// 已拒绝
  PermissionStatusDenied = 1,
/// 尚未请求（未确定）
  PermissionStatusNotDetermined = 2,
};

/// 扫描到的设备信息
SWIFT_CLASS("_TtC7BlueSDK13ScannedDevice")
@interface ScannedDevice : NSObject
/// 设备唯一标识（UUID 字符串）
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
/// 设备广播名称（如 LX-PD02-A1B2）
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceName;
/// 信号强度（RSSI，单位 dBm）
@property (nonatomic, readonly) NSInteger rssi;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 设备铃声类型
/// Sound type
/// DPID=0x6D 用于 APP 下发和设备上报
/// 协议值：0=静音, 1=类型A, 2=类型B, 3=类型C(预留)
typedef SWIFT_ENUM(NSInteger, SoundType, open) {
/// 静音（协议值 0x00）/ Mute
  SoundTypeMute = 0,
/// 声音类型 A（协议值 0x01）/ Sound type A
  SoundTypeTypeA = 1,
/// 声音类型 B（协议值 0x02）/ Sound type B
  SoundTypeTypeB = 2,
/// 声音类型 C（协议值 0x03，预留）/ Sound type C (reserved)
  SoundTypeTypeC = 3,
};

/// 设备时间显示格式
typedef SWIFT_ENUM(NSInteger, TimeFormat, open) {
/// 12 小时制（协议值 0x00）
  TimeFormatHour12 = 0,
/// 24 小时制（协议值 0x01）
  TimeFormatHour24 = 1,
};

/// 设备提醒音量级别
typedef SWIFT_ENUM(NSInteger, VolumeLevel, open) {
/// 低音量（协议值 0x01）
  VolumeLevelLow = 1,
/// 中音量（协议值 0x02）
  VolumeLevelMedium = 2,
/// 高音量（协议值 0x03）
  VolumeLevelHigh = 3,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
