// Generated by Apple Swift version 6.3.1 effective-5.10 (swiftlang-6.3.1.1.2 clang-2100.0.123.102)
#ifndef BLUESDK_SWIFT_H
#define BLUESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BlueSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="BlueSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// 闹钟信息
SWIFT_CLASS("_TtC7BlueSDK9AlarmInfo")
@interface AlarmInfo : NSObject
/// 闹钟槽位索引（1~7）
@property (nonatomic, readonly) NSInteger index;
/// 小时（0~23）
@property (nonatomic, readonly) NSInteger hour;
/// 分钟（0~59）
@property (nonatomic, readonly) NSInteger minute;
/// 星期周期掩码（bit0=周日, bit1=周一, …, bit6=周六，默认 0x7F 每天）
@property (nonatomic, readonly) NSInteger weekMask;
/// 提前取药状态（bit0=当天已取药, bit4=次日已取药）
@property (nonatomic, readonly) NSInteger advanceStatus;
- (nonnull instancetype)initWithIndex:(NSInteger)index hour:(NSInteger)hour minute:(NSInteger)minute weekMask:(NSInteger)weekMask advanceStatus:(NSInteger)advanceStatus OBJC_DESIGNATED_INITIALIZER;
/// 是否为删除状态（所有字段为 0xFF）
@property (nonatomic, readonly) BOOL isDeleted;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK 统一错误类型
/// 所有异步操作通过回调返回此类型，不抛出异常
typedef SWIFT_ENUM(NSInteger, BlueError, closed) {
/// SDK 未初始化，需先调用 initialize()
  BlueErrorNotInitialized = 1,
/// 设备未完成认证，需先完成 authenticate()
  BlueErrorNotAuthenticated = 2,
/// 认证失败，密钥不匹配
  BlueErrorAuthFailed = 3,
/// 指令超时（5秒内未收到设备应答）
  BlueErrorTimeout = 4,
/// 蓝牙权限未授权
  BlueErrorPermissionDenied = 5,
/// 参数无效（如闹钟索引超出 1~7 范围）
  BlueErrorInvalidParameter = 6,
/// 协议错误（帧格式异常或 CRC 校验失败）
  BlueErrorProtocolError = 7,
/// 系统 BLE 错误
  BlueErrorBleError = 8,
/// 设备已断开连接
  BlueErrorDisconnected = 9,
};
static NSString * _Nonnull const BlueErrorDomain = @"BlueSDK.BlueError";

@protocol BlueSDKDelegate;
SWIFT_ENUM_FWD_DECL(NSInteger, LogLevel)
SWIFT_ENUM_FWD_DECL(NSInteger, PermissionStatus)
SWIFT_ENUM_FWD_DECL(NSInteger, ConnectionState)
/// BlueSDK 主入口，采用单例模式
/// 使用方式：<code>BlueSDK.shared.initialize()</code>
SWIFT_CLASS("_TtC7BlueSDK7BlueSDK")
@interface BlueSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) BlueSDK * _Nonnull shared;)
+ (BlueSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <BlueSDKDelegate> _Nullable delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// 初始化 SDK（耗时 ≤ 100ms，NFR04）
- (void)initialize;
/// 销毁 SDK，释放所有 BLE 资源（FR33）
- (void)destroy;
- (void)setLogLevel:(enum LogLevel)level;
/// 查询蓝牙权限状态（FR07）
- (enum PermissionStatus)checkPermissions SWIFT_WARN_UNUSED_RESULT;
/// 当前连接状态（FR06）
@property (nonatomic, readonly) enum ConnectionState connectionState;
/// 断开连接（FR03）
- (void)disconnect;
@end

@class DeviceInfo;
SWIFT_ENUM_FWD_DECL(NSInteger, MedicationStatus)
@class MedicationRecord;
SWIFT_ENUM_FWD_DECL(NSInteger, SoundType)
SWIFT_ENUM_FWD_DECL(NSInteger, TimeFormat)
/// BlueSDK 事件回调协议
/// 所有回调在主线程派发
SWIFT_PROTOCOL("_TtP7BlueSDK15BlueSDKDelegate_")
@protocol BlueSDKDelegate
@optional
/// 连接状态变化（FR04）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didChangeConnectionState:(enum ConnectionState)state;
/// 认证结果（FR09）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didAuthenticateWithSuccess:(BOOL)success error:(enum BlueError)error;
/// 设备信息查询结果（FR12）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didReceiveDeviceInfo:(DeviceInfo * _Nonnull)info;
/// 设备请求时间同步（FR13）
- (void)blueSDKDidRequestTimeSync:(BlueSDK * _Nonnull)sdk;
/// 设备端闹钟变更上报（FR18）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didUpdateAlarm:(AlarmInfo * _Nonnull)alarm;
/// 闹钟开始响铃（FR20）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didAlarmRinging:(NSInteger)alarmIndex alarmInfo:(AlarmInfo * _Nonnull)alarmInfo;
/// 闹钟超时未取药（FR21）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didAlarmTimeout:(NSInteger)alarmIndex alarmInfo:(AlarmInfo * _Nonnull)alarmInfo;
/// 用药结果事件（FR22）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didReceiveMedicationResult:(NSInteger)alarmIndex status:(enum MedicationStatus)status;
/// 用药记录上报（FR23）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didReceiveMedicationRecord:(MedicationRecord * _Nonnull)record;
/// 铃声类型变更上报（FR27）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didChangeSoundType:(enum SoundType)type;
/// 时间格式变更上报（FR31）
- (void)blueSDK:(BlueSDK * _Nonnull)sdk didChangeTimeFormat:(enum TimeFormat)format;
@end

/// BLE 连接状态枚举
/// 状态转换通过 ConnectionManager 统一管理（ARCH-07）
typedef SWIFT_ENUM(NSInteger, ConnectionState, closed) {
/// 已断开（初始状态）
  ConnectionStateDisconnected = 0,
/// 连接中
  ConnectionStateConnecting = 1,
/// 已连接（未认证）
  ConnectionStateConnected = 2,
/// 已认证（可执行业务指令）
  ConnectionStateAuthenticated = 3,
/// 重连中（断线后自动重连）
  ConnectionStateReconnecting = 4,
};

@class NSString;
/// 设备基础信息
SWIFT_CLASS("_TtC7BlueSDK10DeviceInfo")
@interface DeviceInfo : NSObject
/// 固件版本号（如 “1.0.0”）
@property (nonatomic, readonly, copy) NSString * _Nonnull firmwareVersion;
/// 设备 MAC 地址
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
- (nonnull instancetype)initWithFirmwareVersion:(NSString * _Nonnull)firmwareVersion deviceId:(NSString * _Nonnull)deviceId OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// SDK 日志级别
typedef SWIFT_ENUM(NSInteger, LogLevel, closed) {
/// 关闭所有日志（默认）
  LogLevelNone = 0,
/// 仅错误日志
  LogLevelError = 1,
/// 警告及以上
  LogLevelWarn = 2,
/// 信息及以上
  LogLevelInfo = 3,
/// 调试及以上（输出原始帧数据）
  LogLevelDebug = 4,
};

/// 用药记录
SWIFT_CLASS("_TtC7BlueSDK16MedicationRecord")
@interface MedicationRecord : NSObject
/// 用药时间戳（Unix 时间戳，秒）
@property (nonatomic, readonly) NSTimeInterval timestamp;
/// 对应的闹钟槽位索引（1~7）
@property (nonatomic, readonly) NSInteger alarmIndex;
/// 用药状态
@property (nonatomic, readonly) enum MedicationStatus status;
- (nonnull instancetype)initWithTimestamp:(NSTimeInterval)timestamp alarmIndex:(NSInteger)alarmIndex status:(enum MedicationStatus)status OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 用药结果状态枚举
/// 对应协议中 byte9 的状态值
typedef SWIFT_ENUM(NSInteger, MedicationStatus, closed) {
/// 按时取药（0x01）
  MedicationStatusTaken = 1,
/// 超时取药（0x02）
  MedicationStatusTimeout = 2,
/// 漏服（0x03）
  MedicationStatusMissed = 3,
/// 提前取药（0x04）
  MedicationStatusEarly = 4,
};

/// 蓝牙权限状态（与 Android PermissionStatus 对称）
typedef SWIFT_ENUM(NSInteger, PermissionStatus, closed) {
/// 已授权
  PermissionStatusGranted = 0,
/// 已拒绝
  PermissionStatusDenied = 1,
/// 尚未请求（未确定）
  PermissionStatusNotDetermined = 2,
};

/// 扫描到的设备信息
SWIFT_CLASS("_TtC7BlueSDK13ScannedDevice")
@interface ScannedDevice : NSObject
/// 设备唯一标识（UUID 字符串）
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceId;
/// 设备广播名称（如 LX-PD02-A1B2）
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceName;
/// 信号强度（RSSI，单位 dBm）
@property (nonatomic, readonly) NSInteger rssi;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// 设备铃声类型
typedef SWIFT_ENUM(NSInteger, SoundType, closed) {
/// 静音（协议值 0x00）
  SoundTypeMute = 0,
/// 声音类型 A（协议值 0x01）
  SoundTypeTypeA = 1,
/// 声音类型 B（协议值 0x02）
  SoundTypeTypeB = 2,
/// 声音类型 C（协议值 0x03）
  SoundTypeTypeC = 3,
};

/// 设备时间显示格式
typedef SWIFT_ENUM(NSInteger, TimeFormat, closed) {
/// 12 小时制（协议值 0x00）
  TimeFormatHour12 = 0,
/// 24 小时制（协议值 0x01）
  TimeFormatHour24 = 1,
};

/// 设备提醒音量级别
typedef SWIFT_ENUM(NSInteger, VolumeLevel, closed) {
/// 低音量（协议值 0x01）
  VolumeLevelLow = 1,
/// 中音量（协议值 0x02）
  VolumeLevelMedium = 2,
/// 高音量（协议值 0x03）
  VolumeLevelHigh = 3,
};

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
